### PR TITLE
fix: grammar

### PR DESCRIPTION
**Pull request by rin-yato**
- based of english grammar [Perfect Tense](https://www.ef.com/wwen/english-resources/english-grammar/present-perfect/#:~:text=The%20present%20perfect%20of%20any,e.g.%20played%2C%20arrived%2C%20looked.)
- based on [Be going to](https://languagetool.org/insights/post/will-vs-going-to/#:~:text=The%20structure%20of%20using%20going,invite%20him%20to%20the%20party.)

### CODE REVIEW

**Comment by Manethpak** [comment]
hurt my ego, not gonna merge this

**Comment by rin-yato** [comment]
Petition to approve the PR

**Comment by Manethpak** [comment]
@rin-yato thank you xD

**Comment by rin-yato** [comment]
Mad now that u dont merge

**Pull request closed without merging**
